// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';
import { listLocalDatabases } from "@prisma/adapter-d1";

const localD1Dbs = listLocalDatabases();
console.log("TODO: using first listed local database found, but would be better to find by name");
console.log("localD1Dbs", localD1Dbs);

export default defineConfig({
	schema: 'prisma/schema.prisma',
	migrations: {
		path: 'prisma/migrations',
		// seed is not supported in current prisma d1 dx
		// seed: 'node prisma/seed.ts',
	},
	datasource: {
		url: `file:${localD1Dbs[0]}`,
	},
});
